# 1. Copy this file
# 2. Rename the copy to 'application-dev.yml'
# 3. Make sure to add the copy to .gitignore, DO NOT SHARE ON GITHUB
# 4. Fill in your local environment settings

spring:
  # Database connection
  datasource:
    url: YOUR_DATABASE_URL
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: YOUR_DATABASE_USERNAME
    password: YOUR_DATABASE_PASSWORD

  # Hibernate/JPA settings
  jpa:
    hibernate:
      # use 'create-drop' to initialize the DB on first run and after major changes to the model
      # use 'update' otherwise
      ddl-auto: create-drop
    show-sql: true